/* 
 * Creating database schema 
 */
create schema mysat;

/* 
 * Creating table mysat.persona 
 */
create table mysat.persona(
	persona_id bigint not null generated by default as identity (start with 1, increment by 1),
	persona_nombre varchar(30) not null, 
	persona_apellido varchar(30) not null, 
	constraint pk_persona_id primary key (persona_id), 
	constraint uk_per_nombre_apellido unique (persona_nombre, persona_apellido)
);

/* 
 * Creating table mysat.persona_moral 
 */
create table mysat.persona_moral(
	persona_moral_id bigint not null generated by default as identity (start with 1, increment by 1),
	persona_moral_razon_social varchar(80) not null, 
	persona_moral_rfc varchar(15) not null, 
	constraint pk_persona_moral_id primary key (persona_moral_id), 
	constraint uk_permor_razon_social unique (persona_moral_razon_social), 
	constraint uk_permor_rfc unique (persona_moral_rfc)
);

/* 
 * Creating table mysat.nivel_educativo
 */
create table mysat.nivel_educativo(
	nivel_educativo_id bigint not null generated by default as identity (start with 1, increment by 1),
	nivel_educativo_nombre varchar(20) not null, 
	nivel_educativo_tope decimal not null, 
	constraint pk_nivel_educativo_id primary key (nivel_educativo_id), 
	constraint uk_nivedu_nombre unique (nivel_educativo_nombre)
);

/* 
 * Creating table mysat.beneficiario
 */
create table mysat.beneficiario(
	beneficiario_id bigint not null generated by default as identity (start with 1, increment by 1),
	beneficiario_nombre varchar(40) not null, 
	constraint pk_beneficiario_id primary key (beneficiario_id), 
	constraint uk_ben_nombre unique (beneficiario_nombre)
);

/* 
 * Creating table mysat.deduccion
 */
create table mysat.deduccion(
	deduccion_id bigint not null generated by default as identity (start with 1, increment by 1),
	deduccion_nombre varchar(80) not null, 
	constraint pk_deduccion_id primary key (deduccion_id), 
	constraint uk_ded_nombre unique (deduccion_nombre)
);

/* 
 * Creating table mysat.medica
 * references mysat.persona
 */
create table mysat.persona_fisica(
	persona_fisica_id bigint not null generated by default as identity (start with 1, increment by 1),
	persona_fisica_rfc varchar(15) not null, 
	persona_id bigint not null, 
	constraint pk_persona_fisica_id primary key (persona_fisica_id), 
	constraint uk_perfis_rfc unique (persona_fisica_rfc), 
	constraint fk_perfis_persona_id foreign key (persona_id) references mysat.persona (persona_id)
);

/* 
 * Creating table mysat.especialidad_medica 
 * references mysat.nivel_escolar
 */
create table mysat.estudiante(
	estudiante_id bigint not null generated by default as identity (start with 1, increment by 1),
	estudiante_curp varchar(20) not null, 
	persona_id bigint not null, 
	constraint pk_estudiante_id primary key (estudiante_id), 
	constraint uk_est_curp unique (estudiante_curp), 
	constraint fk_est_persona_id foreign key (persona_id) references mysat.persona (persona_id)
);

/* 
 * Creating table mysat.especialidad_medica 
 * references mysat.persona_fisica, mysat.estudiante
 */
create table mysat.persona_fisica_estudiante(
	persona_fisica_estudiante_id bigint not null generated by default as identity (start with 1, increment by 1),
	persona_fisica_id bigint not null,
	estudiante_id bigint not null, 
	constraint pk_persona_fisica_estudiante_id primary key (persona_fisica_estudiante_id), 
	constraint fk_perfisest_persona_fisica_id foreign key (persona_fisica_id) references mysat.persona_fisica (persona_fisica_id), 
	constraint fk_perfisest_estudiante_id foreign key (estudiante_id) references mysat.estudiante (estudiante_id)
);

/* 
 * Creating table mysat.especialidad_medica 
 * references mysat.persona_fisica
 */
create table mysat.factura(
	factura_id bigint not null generated by default as identity (start with 1, increment by 1),
	factura_folio varchar(10) not null, 
	factura_fecha date not null, 
	persona_fisica_id bigint not null, 
	persona_moral_id bigint not null, 
	deduccion_id bigint not null, 
	estudiante_id bigint,
	nivel_educativo_id bigint, 
	beneficiario_id bigint, 
	constraint pk_factura_id primary key (factura_id), 
	constraint fk_fac_persona_fisica_id foreign key (persona_fisica_id) references mysat.persona_fisica (persona_fisica_id), 
	constraint fk_fac_persona_moral_id foreign key (persona_moral_id) references mysat.persona_moral (persona_moral_id), 
	constraint fk_fac_deduccion_id foreign key (deduccion_id) references mysat.deduccion (deduccion_id), 
	constraint fk_fac_estudiante_id foreign key (estudiante_id) references mysat.estudiante (estudiante_id),
	constraint fk_fac_nivel_educativo_id foreign key (nivel_educativo_id) references mysat.nivel_educativo (nivel_educativo_id),
	constraint fk_fac_beneficiario_id foreign key (beneficiario_id) references mysat.beneficiario (beneficiario_id)
);